In [69]:
import pandas as pd
import numpy as np
import re

In [253]:
oed = pd.read_csv('oed_3.csv')
print oed.shape
oed.head()

(3470, 5)

       entry_type  year  part_of_speech          word      month
0  new word entry  2014             n.4          case  September
1  new word entry  2014   adv. and adj.  case-by-case  September
2  new word entry  2014           adj.2      caseless  September
3  new word entry  2014              n.      caseness  September
4  new word entry  2014             n.1    caseworker  September

In [254]:
oed['entry_type']=oed['entry_type'].map(str)
oed['word']=oed['word'].map(str)
oed['month']=oed['month'].map(str)
oed['year']=oed['year'].map(str)
oed['part_of_speech']=oed['part_of_speech'].map(str)

In [255]:
oed['acronym'] = oed['word'].map(lambda x: x==x.upper())
oed[oed['acronym']==True]

          entry_type  year    part_of_speech    word      month acronym
1199  new word entry  2015                n.  FLOTUS       June    True
1223  new word entry  2015                n.     H2O       June    True
1270  new word entry  2015   int. (and adj.)     KKB       June    True
1317  new word entry  2015                n.    SCBU       June    True
1323  new word entry  2015                n.  SCOTUS       June    True
1503   new sub-entry  2015                n.  FLOTUS       June    True
1527  new word entry  2015               n.2     ISA  September    True
1540   new sub-entry  2015                n.     H2O       June    True
1592   new sub-entry  2015               n.2     ISA  September    True
1637   new sub-entry  2015   int. (and adj.)     KKB       June    True
1666  new word sense  2015               n.2     ISA  September    True
1720   new sub-entry  2015                n.    SCBU       June    True
1726   new sub-entry  2015                n.  SCOTUS       June    True
2021  new word sense  2015                n.  FLOTUS       June    True
2064  new word sense  2015                n.     H2O       June    True
2111  new word sense  2015   int. (and adj.)     KKB       June    True
2196  new word sense  2015                n.    SCBU       June    True
2202  new word sense  2015                n.  SCOTUS       June    True
2959  new word entry  2017                n.     420      March    True
3196   new sub-entry  2017                n.     420      March    True
3333  new word sense  2017                n.     420      March    True

In [256]:
oed['dash'] =oed['word'].map(lambda x: re.search('-', x.lower()) != None)
oed['dash'].value_counts()

np.unique(oed[oed['dash']==True]['word'])

array(['-going', '-kine', 'A-rab', 'Belgo-', 'Blu-ray', 'Can-Am',
       'Canadian-American', 'Chi-town', 'Hardy-Weinberg', 'adults-only',
       'anti-unionism', 'bank-switch', 'bank-switched', 'better-heeled',
       'better-paid', 'bluff-charge', 'bluff-charging', 'bug-eyes',
       'bug-out', 'buggered-up', 'case-by-case', 'class-ified', 'dial-in',
       'double-double', 'drink-driver', 'e-cig', 'e-cigarette',
       'e-edition', 'e-skin', 'e-toll', 'ear-grass', 'ear-opening',
       'ear-piercing', 'ear-popping', 'ear-tag', 'ear-tickler',
       'ear-to-ear', 'eye-popping', 'eye-roll', 'eye-roller',
       'eye-rolling', 'eyebrow-raiser', 'eyebrow-raising', 'fact-check',
       'fact-checker', 'fact-checking', 'fair-traded', 'family-style',
       'feed-in', 'fire-bombed', 'fire-setting', 'first-handed',
       'go-for-broke', 'go-for-it', 'go-harvest', 'go-juice',
       'going-about', 'good-enough Morgan', 'grow-op', 'half-ass',
       'halo-halo', 'happy-slappy', 'hard-arse', 'hard-arsed',
       'hard-bodied', 'hard-code', 'hard-coded', 'havey-cavey',
       'high muckety-muck', 'high-centre | high-center',
       'high-centred | high-centered', 'high-centring | high-centering',
       'high-fiving', 'high-full', 'high-graded', 'high-living',
       'high-rider', 'high-riding', 'high-rolling', 'high-stick',
       'hip-hopping', 'house-made', 'large-cap', 'lock-stitched',
       'lock-upable', 'look-see', 'lookie-likie', 'low-balling',
       'low-bridge', 'low-lifer', 'low-maintenance', 'low-rate',
       'low-riding', 'low-top', 'mangia-cake', 'merry-go-around',
       'mini-stroke', 'off-grid', 'old-earth', 'on-trend', 'ooh-wee',
       'sari-sari store', 'say-away', 'scent-mark', 'self-immolate',
       'smash-mouth', 'stick-to-itness', 'sticky-outy', 'stir-fry',
       'stuck-in-the-mud', 'take-back', 'they-all', 'to-go', 'top-rope',
       'tow-netting', 'trade-name', 'trade-up', 'tragico-comedy',
       'tragico-comic', 'tragico-comical', 'uber-', 'un-PC',
       'under-strength', 'water-cycle', 'water-repellence',
       'well-administered', 'well-advanced', 'well-engineered',
       'well-ground', 'well-iqueme', 'well-justified', 'well-observed',
       'well-occupied', 'well-operated', 'well-paced', 'well-paying',
       'well-populated', 'well-positioned', 'well-pressed',
       'well-produced', 'well-provided-for', 'well-rewarded',
       'well-sorted', 'well-supported', 'well-treated', 'white-chinned',
       'white-clawed', 'young-earth'], dtype=object)

In [257]:
oed['word_length'] = oed['word'].map(lambda x: len(str(x).split(' ')))
oed.head()

,entry_type,year,part_of_speech,word,month,acronym,dash,word_length
0,new word entry,2014,n.4,case,September,False,False,1
1,new word entry,2014,adv. and adj.,case-by-case,September,False,True,1
2,new word entry,2014,adj.2,caseless,September,False,False,1
3,new word entry,2014,n.,caseness,September,False,False,1
4,new word entry,2014,n.1,caseworker,September,False,False,1

In [258]:
oed['word_length'].value_counts()

1    2865
2     517
3      79
5       6
4       3
Name: word_length, dtype: int64

In [259]:
oed.sort_values('word_length', ascending=False)

,entry_type,year,part_of_speech,word,month,acronym,dash,word_length
184,new word sense,2014,n.,high centre | high center,September,False,False,5
28,new word entry,2014,n.,high centre | high center,September,False,False,5
455,new sub-entry,2013,n.,grey zone | gray zone,September,False,False,5
541,new word sense,2013,n.,grey zone | gray zone,September,False,False,5
369,new word entry,2013,n.,grey zone | gray zone,September,False,False,5
106,new sub-entry,2014,n.,high centre | high center,September,False,False,5
1000,new word sense,2014,n. and phr.,dulce et decorum est,June,False,False,4
829,new sub-entry,2014,n. and phr.,dulce et decorum est,June,False,False,4
658,new word entry,2014,n. and phr.,dulce et decorum est,June,False,False,4
488,new sub-entry,2013,adj.,non se ipse,September,False,False,3
264,new word entry,2015,n.,Whites tree frog,March,False,False,3
1788,new sub-entry,2015,n.,utang na loob,June,False,False,3
1787,new word entry,2013,adj. (and adv.),la bourgeoise,December,False,False,3
659,new word entry,2014,n.,dulce et decorum,June,False,False,3
118,new sub-entry,2014,n.,high-centring | high-centering,September,False,True,3
117,new sub-entry,2014,adj.,high-centred | high-centered,September,False,True,3
3311,new sub-entry,2017,n. and adj.,South African English,March,False,False,3
116,new sub-entry,2014,v.,high-centre | high-center,September,False,True,3
1556,new sub-entry,2015,int. (and n.),har de har,June,False,False,3
1713,new word sense,2015,n.,watercolouring | watercoloring,September,False,False,3
297,new sub-entry,2015,n.,Whites tree frog,March,False,False,3
1679,new sub-entry,2015,n.,pan de sal,June,False,False,3
2151,new word sense,2015,n.,pan de sal,June,False,False,3
3174,new word entry,2017,n. and adj.,South African English,March,False,False,3
1955,new word entry,2013,n.,embarras de choix,December,False,False,3
76,new word entry,2014,adv. and adj.,year over year,September,False,False,3
1497,new sub-entry,2015,int.,fap fap fap,June,False,False,3
2591,new word entry,2014,n.,good King Henry,December,False,False,3
415,new word entry,2013,adv.,top to tail,September,False,False,3
67,new word entry,2014,adv. and adj.,week by week,September,False,False,3
...,...,...,...,...,...,...,...,...
1314,new word entry,2015,n.,sanger,June,False,False,1
1316,new word entry,2015,n.,say-away,June,False,True,1
1317,new word entry,2015,n.,SCBU,June,True,False,1
1318,new word entry,2015,n.,scenarioist,June,False,False,1
1319,new word entry,2015,v.,scene,June,False,False,1
1298,new word entry,2015,n.,pharmacovigilance,June,False,False,1
1296,new word entry,2015,n.,papsak,June,False,False,1
1271,new word entry,2015,n.,koozie,June,False,False,1
1282,new word entry,2015,n.,merry-go-around,June,False,True,1
1272,new word entry,2015,n.,kryptonite,June,False,False,1
1273,new word entry,2015,n.,kuya,June,False,False,1
1274,new word entry,2015,n.2,lede,June,False,False,1
1275,new word entry,2015,int.,mabuhay,June,False,False,1
1276,new word entry,2015,adv. and adj.,mahala,June,False,False,1
1277,new word entry,2015,n.,Mamil,June,False,False,1
1278,new word entry,2015,n.,mangia-cake,June,False,True,1
1280,new word entry,2015,n.,Masshole,June,False,False,1
1281,new word entry,2015,int. and adj.,meh,June,False,False,1
1283,new word entry,2015,n.,mini-stroke,June,False,True,1
1294,new word entry,2015,n.,pageview,June,False,False,1
1284,new word entry,2015,n.,Morgellons,June,False,False,1
1285,new word entry,2015,n.,nanodiamond,June,False,False,1
1286,new word entry,2015,adj.,nanosized,June,False,False,1
1287,new word entry,2015,n.2,netbook,June,False,False,1
1289,new word entry,2015,adj. and adv.,off-grid,June,False,True,1
1290,new word entry,2015,adj.,old-earth,June,False,True,1
1291,new word entry,2015,v.,onsight,June,False,False,1
1292,new word entry,2015,adj. and adv.,on-trend,June,False,True,1
1293,new word entry,2015,n.,oophagy,June,False,False,1
3469,new word sense,2017,comb._form3,-kine,March,False,True,1